# Generated by Django 3.2.4 on 2021-09-14 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=30)),
                ('imagen', models.ImageField(upload_to=None)),
                ('descripcion', models.TextField(max_length=1000, null=True)),
            ],
        ),
    ]
