# Generated by Django 3.2.4 on 2021-10-17 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactos', '0002_respuestas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
