# Generated by Django 3.2.4 on 2021-10-22 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactos', '0004_remove_contacto_avisos'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacto',
            name='fecha_mensaje',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
