# Generated by Django 3.2.4 on 2021-11-14 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0002_alter_tarea_completado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarea',
            name='completado',
        ),
    ]
