# Generated by Django 3.2.4 on 2021-09-04 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('nombre', models.CharField(max_length=60, primary_key=True, serialize=False)),
                ('descripcion', models.TextField(max_length=300)),
                ('precio', models.IntegerField()),
                ('categoria', models.CharField(choices=[('WHISKY', 'WHISKY'), ('RON', 'RON'), ('GINEBRA', 'GINEBRA'), ('VODKA', 'VODKA'), ('SIN ALCOHOL', 'SIN ALCOHOL')], max_length=20, null=True)),
            ],
        ),
    ]
