# Generated by Django 3.2.4 on 2021-09-02 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plato',
            fields=[
                ('titulo', models.CharField(max_length=60, primary_key=True, serialize=False)),
                ('descripcion', models.TextField(max_length=300)),
                ('precio', models.IntegerField()),
            ],
        ),
    ]
