# Generated by Django 3.2.4 on 2021-09-02 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0002_auto_20210902_1312'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='categoria',
            field=models.CharField(choices=[('WHISKY', 'whisky'), ('RON', 'ron'), ('GINEBRA', 'ginebra')], max_length=10, null=True),
        ),
    ]
