# Generated by Django 3.2.4 on 2021-09-03 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0003_producto_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.CharField(choices=[('WHISKY', 'WHISKY'), ('RON', 'RON'), ('GINEBRA', 'GINEBRA'), ('VODKA', 'VODKA'), ('SIN ALCOHOL', 'SIN ALCOHOL')], max_length=20, null=True),
        ),
    ]
