# Generated by Django 3.2.4 on 2021-09-04 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0004_alter_producto_categoria'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Producto',
        ),
    ]
