# Generated by Django 3.2.4 on 2021-09-04 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0008_reserva_mesa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='mesa',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='usuario',
        ),
        migrations.DeleteModel(
            name='Mesa',
        ),
        migrations.DeleteModel(
            name='Reserva',
        ),
    ]
