# Generated by Django 3.2.4 on 2021-09-04 16:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reservas', '0009_auto_20210904_1635'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mesa',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('lugar', models.CharField(choices=[('EXTERIOR', 'EXTERIOR'), ('INTERIOR', 'INTERIOR')], max_length=20, null=True)),
                ('reservada', models.BooleanField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('clave', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('mesa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='reservas.mesa')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
