# Generated by Django 3.2.4 on 2021-09-06 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0011_evento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='imagen',
            field=models.ImageField(null=True, upload_to='reservas/images'),
        ),
    ]
