# Generated by Django 3.2.4 on 2021-09-07 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0015_alter_evento_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='descripcion',
            field=models.TextField(max_length=1000, null=True),
        ),
    ]
