# Generated by Django 3.2.4 on 2021-09-08 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0017_alter_evento_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mesa',
            name='lugar',
            field=models.CharField(choices=[('EXTERIOR', 'EXTERIOR'), ('INTERIOR', 'INTERIOR')], max_length=20),
        ),
        migrations.AlterField(
            model_name='mesa',
            name='reservada',
            field=models.BooleanField(),
        ),
    ]
