# Generated by Django 3.2.4 on 2021-09-09 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0019_mesa_personas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mesa',
            name='personas',
            field=models.CharField(choices=[('2', '2'), ('4', '4'), ('6', '6'), ('10', '10')], default='4', max_length=20),
        ),
        migrations.AlterField(
            model_name='mesa',
            name='reservada',
            field=models.BooleanField(default=False),
        ),
    ]
