# Generated by Django 3.2.4 on 2021-09-09 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0022_alter_mesa_lugar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mesa',
            name='personas',
            field=models.IntegerField(default=6),
        ),
    ]
