# Generated by Django 3.2.4 on 2021-09-09 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0024_alter_mesa_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mesa',
            name='reservada',
        ),
    ]
