# Generated by Django 3.2.4 on 2021-09-11 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0025_remove_mesa_reservada'),
    ]

    operations = [
        migrations.CreateModel(
            name='MesasDisponibles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('mesa', models.ManyToManyField(to='reservas.Mesa', verbose_name='Mesa disponible')),
            ],
        ),
    ]
