# Generated by Django 3.2.4 on 2021-09-14 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0026_mesasdisponibles'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Evento',
        ),
    ]
