# Generated by Django 3.2.4 on 2021-09-14 13:56

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reservas', '0028_auto_20210914_1355'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mesa',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('lugar', models.CharField(choices=[('EXTERIOR', 'EXTERIOR'), ('INTERIOR', 'INTERIOR')], max_length=20)),
                ('personas', models.IntegerField(default=6)),
                ('fechas_reserva', django.contrib.postgres.fields.ArrayField(base_field=models.DateField(null=True), size=None)),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('clave', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('mesa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='reservas.mesa')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
