# Generated by Django 3.2.4 on 2021-10-22 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reservas', '0030_auto_20211022_1753'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mesa',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('nombre_mesa', models.CharField(max_length=5)),
                ('fecha_reserva', models.DateField(auto_now=True)),
            ],
        ),
    ]
