# Generated by Django 3.2.4 on 2021-10-22 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0031_mesa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mesa',
            name='fecha_reserva',
            field=models.DateField(),
        ),
    ]
