# Generated by Django 3.2.4 on 2021-10-27 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0033_reserva'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='mesas',
        ),
        migrations.DeleteModel(
            name='Mesa',
        ),
        migrations.DeleteModel(
            name='Reserva',
        ),
    ]
