# Generated by Django 3.2.4 on 2021-10-27 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0035_reserva'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reserva',
        ),
    ]
