# Generated by Django 3.2.4 on 2021-10-27 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0037_reserva'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reserva',
            old_name='nombre',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='usuario',
        ),
    ]
