# Generated by Django 3.2.4 on 2021-10-27 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0038_auto_20211027_1242'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reserva',
            old_name='username',
            new_name='nombre_usuario',
        ),
    ]
