# Generated by Django 3.2.4 on 2021-10-27 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reservas', '0040_delete_reserva'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('numero_asistentes', models.IntegerField(choices=[[0, '1'], [1, '2'], [2, '3'], [3, '4']])),
                ('fecha_reserva', models.DateField()),
                ('username', models.CharField(max_length=50)),
            ],
        ),
    ]
