# Generated by Django 3.2.4 on 2021-11-01 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0043_reserva'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='fecha',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
