# Generated by Django 3.2.4 on 2021-11-23 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0045_mesa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mesa',
            name='reserva',
        ),
    ]
