# Generated by Django 3.2.4 on 2021-11-27 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0046_remove_mesa_reserva'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reserva',
        ),
    ]
