# Generated by Django 3.2.4 on 2021-11-27 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0047_delete_reserva'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('numero_asistentes', models.IntegerField(choices=[[0, '1'], [1, '2'], [2, '3'], [3, '4']])),
                ('fecha_reserva', models.DateField()),
                ('username', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=9)),
                ('fecha', models.DateTimeField(auto_now=True)),
                ('horario', models.IntegerField(choices=[[0, '15:00'], [1, '19:00']])),
            ],
        ),
    ]
