# Generated by Django 3.2.4 on 2021-11-27 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0048_reserva'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='horario',
            field=models.IntegerField(choices=[['15:00', '15:00'], ['19:00', '19:00']]),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='numero_asistentes',
            field=models.IntegerField(choices=[['1', '1'], ['2', '2'], ['3', '3'], ['4', '4']]),
        ),
    ]
