# Generated by Django 3.2.4 on 2021-11-27 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0050_auto_20211127_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='horario',
            field=models.IntegerField(choices=[['15:00', '15:00'], ['19:00', '19:00']]),
        ),
    ]
